### ISSUE TITLE
data_format

### ISSUE THREAD

**Issue by andypinxinliu** [athn-nik/motionfix#6]
It seems like the data format is not the conventional 263-dimensional motion representation used in other works. If my understanding is correct, TMR is trained based on this SMPL-H parameter using pose instead of joint locations unlike the original TMR setting.

So, to convert this to the conventional 263, we should flip the y and z, and make y transl be negative, also make the root orient rotate, right?

**Comment by atnikos** [comment]
Hello,

I guess you are talking about the TMR model used for evaluation? Yes, that models is trained on joint rotations (SMPL rotations) and translation deltas. We do this to be directly able to regress and compare SMPL bodies (without SMPlify optimization in the other works that predict joint positions instead). 

It depends what you want to convert and why you want to convert it, but to convert our generations to hml3d features you can take our generations (SMPL rotations and translations) and use their code to compute their features.

I am not sure about the specific details, but imagine our motions (generated) to be exactly like what you will find in an AMASS sequence but canonicalized (initial translation 0, and facing direction the same for all sequences). 

so you could load the motion sequence and start processing it as done from In[7] notebook [here I guess](https://github.com/EricGuo5513/HumanML3D/blob/main/raw_pose_processing.ipynb).

Let me know if I can help further.

**Comment by andypinxinliu** [comment]
Thanks for your additional information!
